import type { CatalogDeviceInput, PlatformSupportInput } from '@lowvolt/schema';
import { p } from './documents.js';
import { cap, port } from './helpers.js';

const altaOnly = (notes: string): Record<string, PlatformSupportInput> => ({
  avigilon_alta: {
    supported: true,
    min_platform_version: null,
    max_platform_version: null,
    min_firmware: null,
    firmware_matrix: [],
    capacity_overrides: [],
    licensing: [{ unit: 'entry', per_child: 'entry' }],
    notes,
    provenance: p('alta_acu'),
  },
  dna_fusion: closed('Avigilon Alta hardware is cloud-bound to Alta Access.'),
  verkada_command: closed('Avigilon Alta hardware is cloud-bound to Alta Access.'),
  lenels2_onguard: closed('Avigilon Alta hardware is cloud-bound to Alta Access.'),
  lenels2_netbox: closed('Avigilon Alta hardware is cloud-bound to Alta Access.'),
});

function closed(notes: string): PlatformSupportInput {
  return {
    supported: false,
    min_platform_version: null,
    max_platform_version: null,
    min_firmware: null,
    firmware_matrix: [],
    capacity_overrides: [],
    licensing: [],
    notes,
    provenance: p('alta_acu'),
  };
}

export const ALTA_DEVICES: CatalogDeviceInput[] = [
  {
    sku: 'OP-ACC',
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Access Control Core',
    class: 'acu',
    display_name: 'Alta Access Control Core (ACU)',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('expansion', 'usb', 2, p('alta_acu'), {
        notes: 'Two expansion-board connections; entry count scales 8 / 12 / 16 with the boards fitted.',
      }),
      port('uplink', 'ethernet', 1, p('alta_acu')),
    ],
    capacities: [
      cap('entry', 16, p('alta_acu'), {
        qualifier: 'Up to 8 / 12 / 16 entries depending on which expansion boards occupy the two connections.',
      }),
      cap('expansion_board', 2, p('alta_acu')),
    ],
    consumes: { bus: 'ip', slots: 1 },
    power: { input_vdc: [12], input_vdc_provenance: p('alta_acu'), aux_output_shared: true },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: altaOnly('Alta Access core controller.'),
    tags: ['alta', 'cloud', 'acu'],
    provenance: p('alta_acu'),
  },
  {
    sku: 'OP-EXP-4',
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Expansion Board',
    class: 'expansion_board',
    display_name: 'Alta 4-Port Expansion Board',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('reader', 'osdp', 4, p('alta_acu'), { modes: ['osdp', 'osdp_secure_channel'], notes: 'Alta Smart Readers.' }),
      port('aux_relay', 'form_c_relay', 2, p('alta_acu')),
      port('aux_input', 'supervised_input', 4, p('alta_acu')),
    ],
    capacities: [cap('entry', 4, p('alta_acu')), cap('reader', 4, p('alta_acu'))],
    consumes: { slots: 1, expansion_slots: 1 },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: altaOnly('4 entries / 4 Smart Readers, plus 2 aux relays and 4 aux inputs.'),
    tags: ['alta', 'expansion'],
    provenance: p('alta_acu'),
  },
  {
    sku: 'OP-EXP-8',
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Expansion Board',
    class: 'expansion_board',
    display_name: 'Alta 8-Port Expansion Board',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('reader', 'osdp', 8, p('alta_acu'), { modes: ['osdp', 'osdp_secure_channel'] }),
    ],
    capacities: [cap('entry', 8, p('alta_acu')), cap('reader', 8, p('alta_acu'))],
    consumes: { slots: 1, expansion_slots: 1 },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: altaOnly('8 entries / 8 Smart Readers.'),
    tags: ['alta', 'expansion'],
    provenance: p('alta_acu'),
  },
  {
    sku: 'OP-EXP-32IN',
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Expansion Board',
    class: 'expansion_board',
    display_name: 'Alta 32-Input Expansion Board',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('input', 'supervised_input', 32, p('alta_acu')),
      port('relay', 'form_c_relay', 2, p('alta_acu'), { notes: 'Wet or dry selectable.' }),
      port('uplink', 'usb', 1, p('alta_acu'), { notes: 'Connects to the ACU via USB.' }),
    ],
    capacities: [cap('input', 32, p('alta_acu')), cap('output', 2, p('alta_acu')), cap('entry', 0, p('alta_acu'))],
    consumes: { bus: 'usb', slots: 1, expansion_slots: 1 },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: altaOnly('32 inputs plus 2 wet/dry relays; USB-connected.'),
    tags: ['alta', 'expansion', 'inputs'],
    provenance: p('alta_acu'),
  },
  {
    sku: 'OP-SDC',
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Single Door Controller',
    class: 'acu',
    display_name: 'Alta Single Door Controller',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('reader', 'osdp', 2, p('alta_acu'), { modes: ['osdp', 'osdp_secure_channel'] }),
      port('uplink', 'poe_pd', 1, p('alta_acu')),
    ],
    capacities: [cap('entry', 2, p('alta_acu')), cap('reader', 2, p('alta_acu'))],
    consumes: { bus: 'ip', slots: 1 },
    power: {
      input_vdc: [],
      aux_output_shared: true,
      poe: { role: 'pd', standard: '802.3at' },
    },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: altaOnly('2 entries / 2 Smart Readers; PoE or PoE+ powered.'),
    tags: ['alta', 'poe', 'single_door'],
    provenance: p('alta_acu'),
  },
  ...([4, 8, 16] as const).map<CatalogDeviceInput>((doors) => ({
    sku: `OP-HUB-${doors}`,
    manufacturer: 'Avigilon (Alta)',
    family: 'Alta Smart Hub',
    class: 'bundle' as const,
    display_name: `Alta ${doors}-Door Smart Hub`,
    lifecycle: { status: 'active' as const, superseded_by: null, eol_date: null },
    ports: [],
    capacities: [cap('entry', doors, p('alta_acu'))],
    consumes: { bus: 'ip' as const, slots: 1 },
    listings: ['UL 294'],
    compliance_flags: ['unknown' as const],
    platform_support: altaOnly(
      `Pre-built ${doors}-door hub: ACU + expansion board(s) + power supply + enclosure.`,
    ),
    tags: ['alta', 'bundle', 'smart_hub'],
    provenance: p('alta_acu'),
  })),
];

export const VERKADA_DEVICES: CatalogDeviceInput[] = [
  {
    sku: 'AC41',
    manufacturer: 'Verkada',
    family: 'AC Series Door Controller',
    class: 'acu',
    display_name: 'Verkada AC41 4-Door Controller',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [port('door', 'osdp_or_wiegand', 4, p('verkada_ac'), { modes: ['osdp', 'wiegand'] })],
    capacities: [cap('door', 4, p('verkada_ac'))],
    consumes: { bus: 'ip', slots: 1 },
    protocols: {
      reader_protocols: ['native_cloud', 'wiegand'],
      mixed_protocol_per_device: true,
      mixed_protocol_per_port: false,
      building_protocols: [],
      provenance: p('verkada_ac'),
    },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: verkadaOnly('4 doors.'),
    tags: ['verkada', 'cloud'],
    provenance: p('verkada_ac'),
  },
  {
    // Acceptance test #4 target.
    sku: 'AC42',
    manufacturer: 'Verkada',
    family: 'AC Series Door Controller',
    class: 'acu',
    display_name: 'Verkada AC42 4-Door Controller',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('door', 'osdp_or_wiegand', 4, p('verkada_ac'), { modes: ['osdp', 'wiegand'] }),
      port('fai', 'fai', 1, p('verkada_ac'), { notes: 'Fire alarm interface.' }),
      port('aux_power', 'aux_power_out', 2, p('verkada_ac'), { notes: '12 V AUX outputs.' }),
    ],
    capacities: [
      cap('door', 4, p('verkada_ac')),
      cap('rex_per_door', 2, p('verkada_ac'), {
        scope: 'per_port',
        scope_ref: 'door',
        qualifier: 'Each door port supports 2 REX devices and 1 DPI (native in/out).',
      }),
      cap('dps_per_door', 1, p('verkada_ac'), { scope: 'per_port', scope_ref: 'door' }),
    ],
    consumes: { bus: 'ip', slots: 1 },
    protocols: {
      reader_protocols: ['native_cloud', 'wiegand'],
      mixed_protocol_per_device: true,
      mixed_protocol_per_port: false,
      building_protocols: [],
      provenance: p('verkada_ac'),
    },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: verkadaOnly('4 doors; adds FAI and 2 REX devices per door port.'),
    tags: ['verkada', 'cloud', 'fai'],
    provenance: p('verkada_ac'),
  },
  {
    sku: 'AC62',
    manufacturer: 'Verkada',
    family: 'AC Series Door Controller',
    class: 'acu',
    display_name: 'Verkada AC62 16-Door Controller',
    lifecycle: { status: 'active', superseded_by: null, eol_date: null },
    ports: [
      port('door', 'osdp_or_wiegand', 16, p('verkada_ac'), { modes: ['osdp', 'wiegand'] }),
      port('fai', 'fai', 1, p('verkada_ac')),
      port('aux_power', 'aux_power_out', 2, p('verkada_ac')),
    ],
    capacities: [cap('door', 16, p('verkada_ac'))],
    consumes: { bus: 'ip', slots: 1 },
    protocols: {
      reader_protocols: ['native_cloud', 'wiegand'],
      mixed_protocol_per_device: true,
      mixed_protocol_per_port: false,
      building_protocols: [],
      provenance: p('verkada_ac'),
    },
    listings: ['UL 294'],
    compliance_flags: ['unknown'],
    platform_support: verkadaOnly('16 doors, 2 AUX, FAI.'),
    tags: ['verkada', 'cloud', 'fai'],
    provenance: p('verkada_ac'),
  },
];

function verkadaOnly(notes: string): Record<string, PlatformSupportInput> {
  const no = (): PlatformSupportInput => ({
    supported: false,
    min_platform_version: null,
    max_platform_version: null,
    min_firmware: null,
    firmware_matrix: [],
    capacity_overrides: [],
    licensing: [],
    notes: 'Verkada AC hardware is cloud-bound to Verkada Command.',
    provenance: p('verkada_ac'),
  });
  return {
    verkada_command: {
      supported: true,
      min_platform_version: null,
      max_platform_version: null,
      min_firmware: null,
      firmware_matrix: [],
      capacity_overrides: [],
      licensing: [{ unit: 'door', per_child: 'door' }],
      notes,
      provenance: p('verkada_ac'),
    },
    dna_fusion: no(),
    avigilon_alta: no(),
    lenels2_onguard: no(),
    lenels2_netbox: no(),
  };
}
